version: '3.8'

services:
  vulnerable:
    build: ./vulnerable-server
    ports:
      - "3000:3000"
    networks:
      - xss-network

  attacker:
    build: ./attacker-server
    ports:
      - "3001:3001"
    networks:
      - xss-network

networks:
  xss-network:
    driver: bridge